import { GitHubConfig } from "../types";

const GITHUB_API_BASE = "https://api.github.com";

export async function validateRepo(config: GitHubConfig): Promise<boolean> {
  const res = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}`, {
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: "application/vnd.github.v3+json",
    },
  });
  return res.ok;
}

export async function getFileTree(config: GitHubConfig): Promise<string[]> {
  // Get the default branch sha first
  const repoRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}`, {
    headers: { Authorization: `Bearer ${config.token}` },
  });
  const repoData = await repoRes.json();
  const defaultBranch = repoData.default_branch;

  const treeRes = await fetch(
    `${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/trees/${defaultBranch}?recursive=1`,
    {
      headers: { Authorization: `Bearer ${config.token}` },
    }
  );
  const treeData = await treeRes.json();
  
  // Filter for blobs (files) and exclude hidden/binary common patterns
  return treeData.tree
    .filter((node: any) => node.type === 'blob' && !node.path.startsWith('.') && !node.path.endsWith('.png') && !node.path.endsWith('.jpg'))
    .map((node: any) => node.path);
}

export async function getFileContent(config: GitHubConfig, path: string): Promise<string> {
  const res = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/contents/${path}`, {
    headers: {
      Authorization: `Bearer ${config.token}`,
      Accept: "application/vnd.github.v3.raw", // Request raw content
    },
  });
  
  if (!res.ok) {
    throw new Error(`Failed to fetch file: ${path}`);
  }
  return await res.text();
}

/**
 * Complex operation:
 * 1. Get SHA of base branch
 * 2. Create new branch ref
 * 3. Create blob (file content)
 * 4. Create tree
 * 5. Create commit
 * 6. Update branch ref
 * 7. Create Pull Request
 */
export async function createPullRequest(
  config: GitHubConfig, 
  path: string, 
  newContent: string, 
  description: string
): Promise<string> {
  const headers = {
    Authorization: `Bearer ${config.token}`,
    Accept: "application/vnd.github.v3+json",
    "Content-Type": "application/json",
  };

  try {
    // 1. Get default branch SHA
    const repoRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}`, { headers });
    const repoData = await repoRes.json();
    const defaultBranch = repoData.default_branch;

    const refRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/ref/heads/${defaultBranch}`, { headers });
    const refData = await refRes.json();
    const baseSha = refData.object.sha;

    // 2. Create new branch
    const branchName = `ai-fix-${Date.now()}`;
    await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/refs`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        ref: `refs/heads/${branchName}`,
        sha: baseSha
      })
    });

    // 3. Create Blob (Content)
    // We strictly use UTF-8 text here
    const blobRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/blobs`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        content: newContent,
        encoding: "utf-8"
      })
    });
    const blobData = await blobRes.json();

    // 4. Create Tree
    const treeRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/trees`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        base_tree: baseSha,
        tree: [{
          path: path,
          mode: "100644",
          type: "blob",
          sha: blobData.sha
        }]
      })
    });
    const treeData = await treeRes.json();

    // 5. Create Commit
    const commitRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/commits`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        message: description || `AI Fix for ${path}`,
        tree: treeData.sha,
        parents: [baseSha]
      })
    });
    const commitData = await commitRes.json();

    // 6. Update Reference (Point branch to commit)
    await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/git/refs/heads/${branchName}`, {
      method: "PATCH",
      headers,
      body: JSON.stringify({
        sha: commitData.sha
      })
    });

    // 7. Create PR
    const prRes = await fetch(`${GITHUB_API_BASE}/repos/${config.owner}/${config.repo}/pulls`, {
      method: "POST",
      headers,
      body: JSON.stringify({
        title: description || `AI Fix for ${path}`,
        body: "Generated by Gemini Pair Programmer",
        head: branchName,
        base: defaultBranch
      })
    });

    const prData = await prRes.json();
    return prData.html_url;

  } catch (error) {
    console.error("PR Creation Failed", error);
    throw new Error("Failed to create Pull Request");
  }
}